### ISSUE TITLE
Add python 3.6 to the build options

### ISSUE THREAD

**Issue by peendebak** [jabooth/condaci#15]
Python 3.6 is the default version for anaconda.

**Comment by jabooth** [comment]
This issue here is how Python 3.6 impacts the Windows build stuff - see [here]:(https://github.com/menpo/condaci/blob/a15f4b29ff800f4bd9267d97510b50d5e9d0dff9/condaci.py#L17)
```python
VS9_PY_VERS = ['2.7']
VS10_PY_VERS = ['3.3', '3.4']
VS14_PY_VERS = ['3.5']
SUPPORTED_PY_VERS = VS9_PY_VERS + VS10_PY_VERS + VS14_PY_VERS
```
is Python 3.6 unchanged from 3.5 from a Windows compiler POV @patricksnape? So safe to move to
```diff
VS9_PY_VERS = ['2.7']
VS10_PY_VERS = ['3.3', '3.4']
- VS14_PY_VERS = ['3.5',]
+ VS14_PY_VERS = ['3.5', '3.6']
SUPPORTED_PY_VERS = VS9_PY_VERS + VS10_PY_VERS + VS14_PY_VERS
```
?

**Comment by patricksnape** [comment]
Yes Python 3.6 is also VS14

**Comment by jabooth** [comment]
@patricksnape @peendebak OK, that's done - in theory 3.6 builds should work fine now.
